
server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    propertes:
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/vehicles
    username: postgres
    password: codeacademy
    driverClassName: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: zalandauskasdarius@gmail.com
    password: paslanx2593
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com